# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Policy < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://aserto.com/"
  version "0.1.10"
  license "Apache License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opcr-io/policy/releases/download/v0.1.10/policy0.1.10_darwin_arm64.zip"
      sha256 "7559181dfd09e460abd7df785f3b926eaf0f02fd592324a97637e71e5abede4a"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.1.10/policy0.1.10_darwin_x86_64.zip"
      sha256 "3be2c237551c16d6436a3dfd5ea671bd49d429557efb6065deea3bebc30b2b67"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opcr-io/policy/releases/download/v0.1.10/policy0.1.10_linux_arm64.zip"
      sha256 "00f0008736f59368e338a3ad25efc4f9828e8c29deb8c8d2c102d9517d5c42f1"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.1.10/policy0.1.10_linux_x86_64.zip"
      sha256 "20644d9e018ec5139f48d295a051cfb3583c55ce2d077dd4d749ec4930c26007"

      def install
        bin.install "policy"
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
