# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyRc < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://aserto.com/"
  version "0.2.0-rc8"
  license "Apache License Version 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc8/policy0.2.0-rc8_darwin_x86_64.zip"
      sha256 "6cefd60169c64c8fbc672746335b6541443c4e8768b565115efabcd0bb70ce5d"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc8/policy0.2.0-rc8_darwin_arm64.zip"
      sha256 "25114d1dbc77e49d0f11eff3c1912cb00e77ba161bec1efe649db1dbf9fef863"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc8/policy0.2.0-rc8_linux_arm64.zip"
      sha256 "fc19ccbbd9f717b02d26220da37ffc8add657bb82f925b49384ee0fe83499184"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc8/policy0.2.0-rc8_linux_x86_64.zip"
      sha256 "c2d833f152296dec4e576c96689fdf17cb7feaa91cc2284f1fe79f154eb4f823"

      def install
        bin.install "policy"
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
