# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyRc < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://aserto.com/"
  version "0.2.0-rc5"
  license "Apache License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc5/policy0.2.0-rc5_darwin_arm64.zip"
      sha256 "a92b4089822eb2427690149f1d10304859139db860c6a61c1c0dfce7bb717627"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc5/policy0.2.0-rc5_darwin_x86_64.zip"
      sha256 "610fd157c17419a85e9c48f7d54da02f82098450a390c1836194e63a935dbd7c"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc5/policy0.2.0-rc5_linux_x86_64.zip"
      sha256 "aae4e4401140b60530d8c62af6f8c5ae383ebd42ed27b00f0a2c9dfc0a68444c"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-rc5/policy0.2.0-rc5_linux_arm64.zip"
      sha256 "de491511cd6bb293dce6aa0837ec228e9054078dcc213ccaa3d34947b14513cc"

      def install
        bin.install "policy"
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
