# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PolicyPre < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://aserto.com/"
  version "0.2.0-pre"
  license "Apache License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-pre/policy0.2.0-pre_darwin_arm64.zip"
      sha256 "3f40ae3dc347f31f2fa4ec1026f27cace6c6d8f14561571981168f635559af60"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-pre/policy0.2.0-pre_darwin_x86_64.zip"
      sha256 "f3fc3a5c1e40e0d2c0eac24d7db280a98e7dbe22c5882855f3d60dda796fc87a"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-pre/policy0.2.0-pre_linux_x86_64.zip"
      sha256 "71b38d65f42642156f72b8d9ff8318e53cd1f70cf464c9206e33d4db8d0fd4e6"

      def install
        bin.install "policy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opcr-io/policy/releases/download/v0.2.0-pre/policy0.2.0-pre_linux_arm64.zip"
      sha256 "8d1467092cd10e2938526c5c81f1bc85c7095f766038cee3a4fb90dc7593d0ec"

      def install
        bin.install "policy"
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
