# This file was generated by GoReleaser. DO NOT EDIT.
cask "policy" do
  name "policy"
  desc "Policy CLI"
  homepage "https://openpolicycontainers.com"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "policy"

  on_macos do
    on_intel do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_darwin_amd64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "a4e4ea8b1d0e1ccd713823b60e8c981dac06a35af2262fa094cfab344fba622d"
    end
    on_arm do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_darwin_arm64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "238ac68da5d6f58b1996231082d2b1db167c7ab59f1042da66c050cbd734ccb5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_linux_amd64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "3c8894d890efb268f3272cb0221c1d1281c97668297c6a63b9680251627820ca"
    end
    on_arm do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_linux_arm64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "48f534708c79758b334740bb88b3d679c142049cd93eb6c67253f65f533acdc8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/policy"]
    end
  end

  # No zap stanza required
end
