# This file was generated by GoReleaser. DO NOT EDIT.
cask "policy" do
  name "policy"
  desc "Policy CLI"
  homepage "https://openpolicycontainers.com"
  version "0.3.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "policy"

  on_macos do
    on_intel do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_darwin_amd64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "8d19699dbfb589e605110dab805ceb1d6e04d497fd26987abf5d189245ee9938"
    end
    on_arm do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_darwin_arm64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "483cdce5ac9a3e5248130059b4e05b51946fb0917ac2d0a96561eb92c9d875c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_linux_amd64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "189fff4ac84eb1e481506609ab469108a4614796d69ef384759150d43bd149cd"
    end
    on_arm do
      url "https://github.com/opcr-io/policy/releases/download/v#{version}/policy_linux_arm64.zip",
        verified: "github.com/opcr-io/policy"
      sha256 "0ff7dc40e3c6df2b7636ced12539dc8ad8d4e55fbbd5ec8f309ef4c12ac604fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/policy"]
    end
  end

  # No zap stanza required
end
